### ISSUE TITLE
Placeholder number

### ISSUE THREAD

**Issue by cayasso** [amarofashion/react-credit-cards#13]
Does this support something like this?

![image](https://user-images.githubusercontent.com/42518/32253699-f576784e-be61-11e7-99a7-b16d1e1d106e.png)

It would be cool that we can also display a card in this way so it can be edited. Is this possible?

**Comment by gilbarbara** [comment]
hey,

What do mean with "like this"?
A preview box with saved data but not the full-fledged card? Without colors?

**Comment by cayasso** [comment]
Exactly!!!

**Comment by gilbarbara** [comment]
Please check version 0.7

**Comment by gabrielpereirapinheiro** [comment]
it's possible hidde the 'valid thru' field ?
