### ISSUE TITLE
Remove sourceMappingURL from css files

### ISSUE THREAD

**Issue by MikeDevice** [amarofashion/react-credit-cards#14]
Now there is a problem with `sourceMappingURL`.
I don't use `sass` in my project and I include `.css` file. So when I include [styles-compiled.css](https://github.com/amarofashion/react-credit-cards/blob/master/lib/styles-compiled.css), I get follow error:

```
css/styles-compiled.css.map for is not found
```
I don't want to include sourcemap, because it's overhead

**Comment by gilbarbara** [comment]
will do.

**Comment by gilbarbara** [comment]
Fixed in a708c2e59aa8b0a1c9df283e83f7f6ad926e2f44
