### ISSUE TITLE
cvc flip not animating

### ISSUE THREAD

**Issue by jennykortina** [amarofashion/react-credit-cards#16]
I am using react-credit-cards in conjunction with redux forms.  I have everything working except the cvc animation.  It does not flip the card over.  Any suggestions on what to try?

My code is here: https://gist.github.com/jennykortina/f7481dfdf56a49290a7d5f0ae378ebb6

Awesome work thank you!

**Comment by gilbarbara** [comment]
Hey @jennykortina 

You should set the `focused` prop with "cvc" for the card to rotate.
But even better would be to change this `focused` prop for every corresponding filed using the`onFocus` event listener.

input.onFocus -> setState `focused` to input's name -> pass this state property to the `focused` prop

**Comment by jennykortina** [comment]
Thank you!
