### ISSUE TITLE
Issue with IE11 Display of CSV Number on Back of Card

### ISSUE THREAD

**Issue by pacarvalho** [amarofashion/react-credit-cards#17]
The component is not behaving properly when the card flips over to show the back for the user to input their CSV. 

![image](https://user-images.githubusercontent.com/860599/34268537-e52f80b8-e65f-11e7-86fb-2cc07fa0eeda.png)

**Comment by gilbarbara** [comment]
Yes, it is a known limitation on IE 11. Please check #4
