### ISSUE TITLE
VISA card number length

### ISSUE THREAD

**Issue by dlong500** [amarofashion/react-credit-cards#2]
Apparently there are some newer VISA cards with 19 digits.  However, the card visualizer doesn't show any digits beyond 16.  Can this be fixed?

**Comment by cassiocardoso** [comment]
Hey @dlong500 sorry for taking so long to answer. We're looking into it and will ship a fix in the next couple days.

**Comment by gilbarbara** [comment]
Hey @dlong500 
Updated support for 19 digits added in 2c47cd64f1030eca59acc514f2ba1926a1c43856 (v0.4.1)

👍🏻
