### ISSUE TITLE
update mastercard gradient

### ISSUE THREAD

**Issue by gilbarbara** [amarofashion/react-credit-cards#22]
Too much orange and interferes with the logo colors

**Comment by zethussuen** [comment]
I would agree with @gilbarbara here. After browsing through mastercard's brand guidelines, although they don't specify a standard background, their logomark requirements recommend either a dark or light background. I would use a (light) white to (light) grey gradient similar to the one in effect for diner's club.

![image](https://user-images.githubusercontent.com/754158/45445333-eef2b300-b697-11e8-89eb-9ea01da7d650.png)
![image](https://user-images.githubusercontent.com/754158/45445321-e7330e80-b697-11e8-9cb8-4f15cd715ddf.png)

References:
- https://brand.mastercard.com/brandcenter/mastercard-brand-mark.html
- https://www.mastercard.us/en-us/consumers/find-card-products/debit-cards.html
