### ISSUE TITLE
Using component with Dashlane autocomplete

### ISSUE THREAD

**Issue by redlock** [amarofashion/react-credit-cards#26]
Hi,
I use Dashlane for password management. When using the component in a page with Dashlane's extension for auto-completion, the valid-thru field becomes too small. 
Here is a screenshot:

<img width="791" alt="screen shot 2018-09-19 at 8 43 37 am" src="https://user-images.githubusercontent.com/438431/45733185-784e3c00-bbe8-11e8-8996-091f9d6dca64.png">

**Comment by gilbarbara** [comment]
This library is about the card preview, not the form UI, so you can customize the form any way you want.
