### ISSUE TITLE
Preview

### ISSUE THREAD

**Issue by scarranca** [amarofashion/react-credit-cards#29]
Hi, it`s an awesome dependency thanks.
But preview is not working

**Comment by Neaox** [comment]
In what way is it not working?

**Comment by magnito2** [comment]
Hi. I need some help on what I believe is a related issue. I am using the library to preview the cards, and all seems to work, but I cant figure out how to show data when the only available information I have is the last4 digits of the credit cards. I want it to show something like **** **** **** 1234 is the card number, but prefixing with 12 stars is not working for say mastercard.
