### ISSUE TITLE
Support for Troy credit cards

### ISSUE THREAD

**Issue by medetcan** [amarofashion/react-credit-cards#34]
Hello, Can you add support for Troy credit cards or i can send a PR but i am unable to reproduce the steps that specified within the Contributing.md file to get project going.

Troy credit card patterns : /^(?:9792|65\d{2}|36|2205)\d{12}$ /

**Comment by gilbarbara** [comment]
Hey

This library uses [Payment](https://github.com/jessepollak/payment) to validate cards. You should ask them to add it.

[s]
