### ISSUE TITLE
Safari Back of Card Display Issues

### ISSUE THREAD

**Issue by cody-young** [amarofashion/react-credit-cards#37]
In Safari 12.0.3 on mac, the back of card was displaying like this:
![image](https://user-images.githubusercontent.com/4195563/55433770-e89c2980-554a-11e9-8ade-ddf482650688.png)

I had to add this to fix it:
```
.rccs_card, .rccs__card--front {
  -webkit-backface-visibility: hidden;
}

**Comment by gilbarbara** [comment]
Hey,

backface-visibility is already [set](https://github.com/amarofashion/react-credit-cards/blob/master/src/styles.scss#L81).
You need to process your styles with post-css or autoprefixer.

**Comment by cody-young** [comment]
Ahh, that explains it. Thanks for the tip!

**Comment by luismramirezr** [comment]
> Hey,
> 
> backface-visibility is already [set](https://github.com/amarofashion/react-credit-cards/blob/master/src/styles.scss#L81).
> You need to process your styles with post-css or autoprefixer.

So, this happened to me, but currently, I'm in the developing stage and haven't made a build. I think that after the build it will work fine. 

Do you think this information is worth to be in the documentation?
