### ISSUE TITLE
Improvement on "focus" field README.md

### ISSUE THREAD

**Issue by Jonathan0wh** [amarofashion/react-credit-cards#38]
It is a really nice component. But the documentation could be improved (mainly about some requirement on input fields for the card number, expired date and CVC). For example, maybe it is better to specify that one would need to give their input **special and fixed input name** for the focus function:

```<Input name="name" />``` for name input: **name="name"** required
```<Input name="number" />``` for card number input: **name="number"** required
```<Input name="expiry" />``` for expired date input: **name="expiry"** required
```<Input name="cvc" />``` for cvc input: **name="cvc"** required

or the focus feature such as ```<Card focused="expiry" />``` would not work.
Or maybe it would be even better to allow users to customise their input name, and set a way for ```<Card name="" cardNumber="" expiry="" cvc="" />``` to read those custom input names, like
```
<Card 
    inputNames={
       name: "my input name for the card name"
       cardNumber: "my input name for the card number"
       expiry: "my input name for the expire date"
       cvc "my input name for the cvc"
    }
```
because ```<Card />``` prop names like _name_, _number_ seems to be pretty common?

Besides, it may also be beneficial for developers to integrate ```formatCreditCardNumber``` ```formatCVC``` ```formatExpirationDate``` and Payment plugin in your code example into this repo as API functions because similar functions are usually used together with card payment.

**Comment by paulenokels** [comment]
You are absolutely correct, the documentation on "focused" prop is poor

**Comment by mandazi** [comment]
I agree with this.

**Comment by gilbarbara** [comment]
Feel free to submit a PR to improve it.
