### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by fidelman** [amarofashion/react-credit-cards#4]
Hello guys,
Thank you very much for your component. It is awesome.
In IE11 the Card component is not rendered. The console is empty and a page is empty. Your deployed [link](https://amarofashion.github.io/react-credit-cards/) also is empty. 
Is it possible to use this great component in IE11?
Thank you.

**Comment by cassiocardoso** [comment]
Hi @fidelman we tested this today and this is a know issue on IE 11 that it doesn't support `transform-style: preserve-3d` as noted [here](https://msdn.microsoft.com/library/hh673529(v=vs.85).aspx#the_ms_transform_style_property).

I would recommend that you use Modernizr or add some class to `.rccs` on your side to handle this issue.

**Comment by pacarvalho** [comment]
@gilbarbara Wouldn't it be better to add the required changes on this module so that it is self contained?

**Comment by gilbarbara** [comment]
@pacarvalho Feel free to open a PR with a fix for this.
