### ISSUE TITLE
How to mask card number

### ISSUE THREAD

**Issue by iamRamkumar** [amarofashion/react-credit-cards#43]
is there any way to **mask credit card number.**

I want to mask number like this  `"**** **** **** 4242"`

I am Invoking the component like below:

```
<Cards number={parsedNumber} name={name} expiry={expiry} 
               cvc={cvc} focused={focused} acceptedCards={acceptedCards}
               callback={this.handleCallback} preview={true} />
```

Expected the number will be shown like this  `"**** **** **** 4242"`. but actual number is showing on the card

**Comment by gilbarbara** [comment]
The `preview` prop is used to allow you to set a "saved" number with masked characters and still show the branded card.
It won't mask the number for you.

**Comment by iamRamkumar** [comment]
thanks @gilbarbara 

I missed passing `issuer` **prop** to **_Card_** component. now I am able to show number like this `"**** **** **** 4242"`
