### ISSUE TITLE
CVC not flipping when focused

### ISSUE THREAD

**Issue by linconkusunoki** [amarofashion/react-credit-cards#45]
Hi, I was testing  in the sandbox with the provided credit card numbers in [this link](https://developers.ebanx.com/guides/going-live/test-card-numbers/), and when I paste the Amex numbers the CVC flip effect has stopped working. The other card numbers work properly.

**Comment by gilbarbara** [comment]
The Amex card doesn't flip at all since the CVC code is in the front of the card.
View the explanation [here](https://www.cvvnumber.com/cvv.html).
