### ISSUE TITLE
Text is displayed in reverse on Safari when entering CVC

### ISSUE THREAD

**Issue by poisonWinslow** [amarofashion/react-credit-cards#49]
When entering the CVC on Safari, the card does not flip to the back side of the card and mirrors all of the data on the front of the card

![image](https://user-images.githubusercontent.com/42157052/63855561-afd37580-c96d-11e9-9675-829af2a52720.png)

**Comment by gilbarbara** [comment]
Which Safari version? I couldn't reproduce

**Comment by gilbarbara** [comment]
Did you try the fix in #37 ?
