### ISSUE TITLE
Amex and Diners maxLength

### ISSUE THREAD

**Issue by kaisermann** [amarofashion/react-credit-cards#50]
Hi! First of all, thanks for this great component :) 

I've hit an issue where the `maxLength` property for `AMEX` (15 chars + 2 spaces = 17) and `DINERS` (14 chars + 2 spaces = 16) doesn't count the `spaces` in contrast to the `maxLength` for `MASTER` and `VISA` (16 chars + 3 spaces = 19)

https://github.com/amarofashion/react-credit-cards/blob/fea2e002aa63b707cf697b4ae236738c237ad329/src/index.js#L185

Is this the expected behavior? Thanks 😁

**Comment by gilbarbara** [comment]
Hey,

These limits aren't supposed to include spaces. You can check the limits [here](https://github.com/jessepollak/payment/blob/master/src/index.coffee#L5) and [here](https://creditcardgenerator.com/american-express-card-number-format/card/)

**Comment by kaisermann** [comment]
Oh okay! Thanks for the quick response 😁
