### ISSUE TITLE
Preview not working for masking the number

### ISSUE THREAD

**Issue by theone3nu** [amarofashion/react-credit-cards#53]
I want to mask the credit card in the preview. I have added preview prop but still i can see the unmasked numbers. Please find the code below.
```

`
`import React from 'react';
import Cards from 'react-credit-cards';





export default class App extends React.Component {
  state = {
    cvc: '',
    expiry: '',
    focus: '',
    name: '',
    number: '',
    preview: true,
    issuer: 'visa'
  };
 
  handleInputFocus = (e) => {
    this.setState({ focus: e.target.name });
  }
  
  handleInputChange = (e) => {
    const { name, value } = e.target;
    
    this.setState({ [name]: value });
  }
  
  render() {
    return (
      <div id="PaymentForm">
        <Cards
          cvc={this.state.cvc}
          expiry={this.state.expiry}
          focus={this.state.focus}
          name={this.state.name}
          number={this.state.number}
          preview={this.state.preview}
          issuer={this.state.issuer}
        />
        <form>
        	<input
            type="tel"
            name="number"
            placeholder="Card Number"
            onChange={this.handleInputChange}
            onFocus={this.handleInputFocus}
          />
         
        </form>
      </div>
    );
  }
}`
```

**Comment by gilbarbara** [comment]
The `preview` flag allows you to set a string as the card's number instead of just numbers.
It won't mask the characters for you. Try:

```js
const cardNumber = '4111 1111 1111 1111';

<CreditCard
 number={cardNumber.replace(/\d{4}(?= \d{4})/g, "****")}
 preview
/>

```

**Comment by bfitec** [comment]
The docs on this are kind of confusing, I had the same issue... If you'd like I can clarify them and add an example for a card preview and make a PR @gilbarbara

**Comment by theone3nu** [comment]
Thanks for the reply. If i give the static value then it works perfect. But i want the card number to be masked on change of the card input. It is becoming grey when i type first 5 digits. Since the card number is taking as asterisk symbol it is not valid. Any help on this?

**Comment by gilbarbara** [comment]
@theone3nu you can obfuscate the card number when the number input changes and save it in the component state that way

**Comment by Jj2martinez** [comment]
Seems the only way to set the styling of the payment methods it's with the first 2 numbers but if you use '****' in the first characters, it can't get it. It's possible to set the brand (visa mastercard) styling without the numbers? 
Example: 
`<Cards
      type='visa'
  />`
