### ISSUE TITLE
Card wont focus on fields

### ISSUE THREAD

**Issue by sabatsu** [amarofashion/react-credit-cards#59]
I am implementing this into my app and can't get it to focus on the fields. It just stays dark whenever you touch one of the fields and won't turn the card to the backside whenever you touch the CVC field.

**Comment by gilbarbara** [comment]
Are you setting the `focused` prop to the correct value?
Show some code

**Comment by sabatsu** [comment]
yes. I think I am.
here some code..

The cards component:
`<Cards
              cvc={this.state.cvc}
              expiry={this.state.expiry}
              focus={this.state.focus}
              name={this.state.name}
              number={this.state.number}
            />
Input example:
<input
                type="tel"
                name="cvc"
                placeholder="CVC"
                required
                onChange={this.handleCCInputChange.bind(this)}
                onFocus={this.handleCCInputFocus.bind(this)}
              />

The handlers:
`handleCCInputFocus(e) {
    this.setState({ focus: e.target.name });
  }
  
  handleCCInputChange(e) {
    const { name, value } = e.target;
    this.setState({ [name]: value });
  }`

**Comment by sabatsu** [comment]
I found the answer using your comment. The `focused` was once `focus` and it didnt work. Change the property to `focused`.
Thanks
