### ISSUE TITLE
Handle click on Cards component

### ISSUE THREAD

**Issue by TedSean** [amarofashion/react-credit-cards#60]
Hello,

I would like to implement `onClick` event on Cards component to be able to delete the cards that are displayed, Is there a way out ?

```js
import Cards from "react-credit-cards";

<Cards
      cvc=""
      expiry="**/**"
      name={``}
      number={``}
      preview={true}
      onClick={}
 />
```

**Comment by gilbarbara** [comment]
Hey

It's not possible. You can wrap the card with your own component and handle this by yourself
