### ISSUE TITLE
It is possible change values of scss variables ?

### ISSUE THREAD

**Issue by hnrqsss** [amarofashion/react-credit-cards#64]
Hello, thanks for your lib its amazing.

How can i change the the sccs values?
For example: $rccs-name-font-family: whaterver;

I try to 
```
@import '../../../../node_modules/react-credit-cards/lib/styles.scss';

$rccs-size: 350px !default;
```

**Comment by gilbarbara** [comment]
Yes,

Just set the variables BEFORE you import the SCSS file.
And you don't need to set `!default` on the variables.
