### ISSUE TITLE
Diners format

### ISSUE THREAD

**Issue by gleidsonh** [amarofashion/react-credit-cards#70]
I'm using this test card diners with 14 digits: 3056 930902 5904

However, on typing numbers, react credit cards component expect a last digit: https://prnt.sc/rmscy4

On preview is showing as it has 15 digits, not 14 digits: https://prnt.sc/rmsdjy

**Comment by luismramirezr** [comment]
Almost same here.

Without `preview` prop it works fine.
When in use, I got 15 preview digits but it returns `maxLength = 14` from `callback`.

**Comment by gilbarbara** [comment]
This is being tracked in #79
