### ISSUE TITLE
How i can use props like placeholders

### ISSUE THREAD

**Issue by agaitan26** [amarofashion/react-credit-cards#73]
Hi im trying to use in <Card section this 

placeholders={ name: 'YOUR NAME HERE' } to change default text, but i think im doing it wrong. How i can use that prop?

```
          <Card
            number={number}
            name={name}
            expiry={expiry}
            cvc={cvc}
            focused={focused}
            placeholders={ name: 'YOUR NAME HERE' }
            callback={this.handleCallback}
          />
```

thank you

**Comment by carlosasj** [comment]
Hey @agaitan26 
You should pass an object to the prop:
```
placeholders={{ name: 'YOUR NAME HERE' }}
```
(notice the double curly brackets)

**Comment by agaitan26** [comment]
great, thank you very much
