### ISSUE TITLE
Credit Card number starting as "2326" the library is mapping a MasterCard issuer

### ISSUE THREAD

**Issue by christian-manrique** [amarofashion/react-credit-cards#85]
Hi, i have a quick question how can i  remove certain starting numbers avoiding to get any credit card issuer, i am typing "2326" and  am getting Master Card as result, however there  is a fact than MasterCard  CC numbers starts at 5, let me attach a screenshot about what am saying. my application is in react version is  ^16.2.0 and  react-credit-cards  is 0.8.0. Any suggestion would be pretty helpful thanks

![image](https://user-images.githubusercontent.com/992281/89041165-e8fd2e00-d312-11ea-9023-0cbeeadbb06c.png)

**Comment by gilbarbara** [comment]
Hey @christian-manrique 

Actually Mastercard uses a few other prefixes, including 2xxx.
Check this [list](https://docs.adyen.com/development-resources/test-cards/test-card-numbers#mastercard).

**Comment by christian-manrique** [comment]
@gilbarbara  thank for the information pal!
