### ISSUE TITLE
Expiration date placeholder support

### ISSUE THREAD

**Issue by fkoner** [amarofashion/react-credit-cards#86]
Could you add support for the expiration date placeholder?

To use it as follows:

```jsx
<Card
    name="Francisco Urquijo"
    number="5555 4444 3333 1111"
    expiry="12/2024"
    cvc="236"
    placeholders={{
        name: 'Titular',
        expiry: 'Vence hasta',
    }}
/>
```

It is very convenient when working with languages other than English.

**Thanks in advance**

**Comment by gilbarbara** [comment]
Hey

There's a `locale` prop to change the expiration text

**Comment by fkoner** [comment]
Thanks @gilbarbara !
