### ISSUE TITLE
Customization of form with separate fields

### ISSUE THREAD

**Issue by waleedarshad** [amarofashion/react-credit-cards#9]
Do it support fully customize of the fields look and fields and fields showing seperating. how to put validations

**Comment by gilbarbara** [comment]
¯\_(ツ)_/¯

**Comment by waleedarshad** [comment]
@gilbarbara i did not get you.

Would you please explain?

**Comment by waleedarshad** [comment]
@gilbarbara my requirements are something like that
![requirment_card](https://user-images.githubusercontent.com/5329697/29957808-d78067e2-8f08-11e7-82ca-f9841bc49be1.png)
