### ISSUE TITLE
preview property to censor credit card number doeswork

### ISSUE THREAD

**Issue by goffxnca** [amarofashion/react-credit-cards#93]
preview property to censor credit card number doeswork,

        <Cards
          cvc={props.cardInfo.cardCVCCode}
          expiry={props.cardInfo.cardExpireDate}
          name={props.cardInfo.cardHolderName}
          number={props.cardInfo.cardNumber}
          preview={true}
        />

Event I set it to true, It still show whole actual credit card number, any help?

**Comment by gilbarbara** [comment]
hey @goffxnca 

As described in the README

```
preview {bool}: To use the card to show scrambled data (e.g. **** 4567).
issuer {string}: Set the issuer for the preview mode (e.g. visa|mastercard|...)
```

Preview doesn't scramble the date, just allow you to use it.

**Comment by goffxnca** [comment]
thanks that does help.
