### ISSUE TITLE
Is it possible to change the 'Your name here' and 'valid thru' labels on card?

### ISSUE THREAD

**Issue by andrebrito** [amarofashion/react-credit-cards#96]
This is not an issue per se, just a random doubt that I have.
Can I cange dynamically the 'Your name here' and 'valid thru' labels on the card?

Thanks a lot!

**Comment by Charlo270398** [comment]
Try with this: 
![image](https://user-images.githubusercontent.com/32102276/103275197-ed15a080-49c3-11eb-8403-3482a5dd8103.png)
![image](https://user-images.githubusercontent.com/32102276/103275206-f868cc00-49c3-11eb-8db2-9fc3f0083e82.png)

**Comment by wylkon** [comment]
You can change the text "Your name here" using the `placeholders` prop and "valid date" in locale prop.

Take a look in the README: https://github.com/amarofashion/react-credit-cards#props

---


```js
<Card
  number={number}
  name={name}
  expiry={expiry}
  cvc={cvc}
  focused={focused}
  callback={this.handleCallback}
  placeholders={{name: 'YOUR CUSTOM PLACEHOLDER'}}
  locale={{valid: 'CUSTOM DATE'}}
/>
